<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="stopping_mode" Id="{65ab387d-14b6-4597-8712-6f6f31d5a03f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM stopping_mode
VAR
	ed_routine_stopping_idle: BOOL;
	stack_power_enabled: BOOL;
	RECTIFIER_OUTPUT_OFF: BOOL;// ADD LOGIC FOR MONITORING RECTIFIER OUTPUT - USE CT? VERIFY PS DOES NOT MOVE CURRENT WHEN POWERED OFF
	u_3112_stop_request: BOOL;
	u_3212_stop_request: BOOL;
	u_3312_stop_request: BOOL;
	u_3405_stop_request: BOOL;
	u_3160_stop_request: BOOL
;
	u_3260_stop_request: BOOL;
	u_3360_stop_request: BOOL;
	u_3370_stop_request: BOOL;
	u_3112_run_feedback: BOOL;
	u_3212_run_feedback: BOOL;
	u_3312_run_feedback: BOOL;
	u_3405_run_feedback: BOOL;
	u_3160_run_feedback: BOOL;
	u_3260_run_feedback: BOOL;
	u_3360_run_feedback: BOOL;
	u_3370_run_feedback: BOOL;
	
	nv_3110_stop_request:BOOL;
	av_3248_stop_request: BOOL;
	av_3148_stop_request: BOOL;
	nv_3335_stop_request: BOOL;
	nv_3235_stop_request: BOOL;
	nv_3135_stop_request: BOOL;
	nv_3310_stop_request: BOOL;
	nv_3210_stop_request: BOOL;
	ed_routine_stop_mode: BOOL;
	redox_doser_stop_request: BOOL;
	nv_3335_position_request: INT;
	av_3148_position_request: INT;
	av_3248_position_request: INT;
	ed_pumps_stopped: BOOL;

	nv_3335_position_feedback: INT;
	nv_3335_recycle_position: BOOL;
	av_3148_position_feedback: INT;
	av_3148_recycle_position: BOOL;
	av_3248_recycle_position: BOOL;
	ed_valves_stopped: BOOL;
	ed_stopped: BOOL;
	av_3348_position_request: INT;
	nv_3372_stop_request: BOOL;
	av_3348_position_feedback: INT;
	av_3348_recycle_position: BOOL;
	nv_3335_closed_feedback: BOOL;
	nv_3372_closed_feedback: BOOL;
	nv_3162_stop_request: BOOL;
	ed_critical_stop: BOOL;
	tmr_stop_pump_delay: TON;
	tmr_stop_pump_delay_pt: TIME := T#10S;
	tmr_stop_pump_delay_et: TIME;
	test_ramp: ramp;
	eng_test: BOOL;
	test_ramp_start_val: REAL;
	test_ramp_end_val: REAL;
	test_ramp_duration: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"stack_power_enabled"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">15L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"OR"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">""</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">416L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" />
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"general.ed_routine_stop"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">14L</v>
                            </o>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"general.ed_critical_stop"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">419L</v>
                            </o>
                            <v n="Id">418L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <v n="CallType" t="Operator">Or</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">417L</v>
                      </o>
                      <v n="Id">16L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">12L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"u_3112_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">579L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_u_3112_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">19L</v>
                          </o>
                          <o>
                            <v n="Operand">"u_3212_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_u_3212_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">581L</v>
                          </o>
                          <o>
                            <v n="Operand">"u_3312_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_u_3312_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">582L</v>
                          </o>
                          <o>
                            <v n="Operand">"u_3405_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">33L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0091_u_3405_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">583L</v>
                          </o>
                          <o>
                            <v n="Operand">"u_3160_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">32L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_u_3160_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">584L</v>
                          </o>
                          <o>
                            <v n="Operand">"u_3260_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">31L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_u_3260_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">585L</v>
                          </o>
                          <o>
                            <v n="Operand">"u_3360_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_u_3360_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">586L</v>
                          </o>
                          <o>
                            <v n="Operand">"u_3370_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">103L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_u_3370_hmi_start_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">587L</v>
                          </o>
                          <o>
                            <v n="Operand">"redox_doser_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">23L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"MOVE"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">""</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">741L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"opc.popa_0081_idle_pressure_setpoint_request"</v>
                              <v n="Type">"LREAL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">743L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeBox">
                            <v n="BoxType">"OR"</v>
                            <o n="Instance" t="Operand">
                              <n n="Operand" />
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">421L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems" />
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems" cet="BoxTreeOperand">
                              <o>
                                <o n="Operand" t="Operand">
                                  <v n="Operand">"general.ed_routine_stop"</v>
                                  <v n="Type">"BOOL"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">true</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">102L</v>
                                </o>
                                <v n="Id">101L</v>
                              </o>
                              <o>
                                <o n="Operand" t="Operand">
                                  <v n="Operand">"general.ed_critical_stop"</v>
                                  <v n="Type">"BOOL"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">true</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">426L</v>
                                </o>
                                <v n="Id">425L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <v n="CallType" t="Operator">Or</v>
                            <n n="EN" />
                            <n n="ENO" />
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">422L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"0"</v>
                              <v n="Type">"INT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">745L</v>
                            </o>
                            <v n="Id">744L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v></v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v></v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">Move</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">742L</v>
                      </o>
                      <v n="Id">10L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"nv_3110_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">568L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3110_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">176L</v>
                          </o>
                          <o>
                            <v n="Operand">"nv_3210_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">569L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3210_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">571L</v>
                          </o>
                          <o>
                            <v n="Operand">"nv_3310_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">570L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3310_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">572L</v>
                          </o>
                          <o>
                            <v n="Operand">"nv_3135_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">179L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3135_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">574L</v>
                          </o>
                          <o>
                            <v n="Operand">"nv_3235_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">270L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3235_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">575L</v>
                          </o>
                          <o>
                            <v n="Operand">"nv_3335_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">271L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3335_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">576L</v>
                          </o>
                          <o>
                            <v n="Operand">"nv_3372_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">358L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3372_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">577L</v>
                          </o>
                          <o>
                            <v n="Operand">"nv_3162_stop_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">180L</v>
                          </o>
                          <o>
                            <v n="Operand">"opc.popa_0081_nv_3162_hmi_open_request"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">578L</v>
                          </o>
                          <o>
                            <v n="Operand">"ed_pumps_stopped"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">181L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"MOVE"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">""</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">820L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"opc.popa_0081_av_3348_hmi_position_request"</v>
                              <v n="Type">"LREAL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">822L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeBox">
                            <v n="BoxType">"MOVE"</v>
                            <o n="Instance" t="Operand">
                              <n n="Operand" />
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">141L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems" cet="Operand">
                                <n />
                                <o>
                                  <v n="Operand">"av_3348_position_request"</v>
                                  <v n="Type">"INT"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">true</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">143L</v>
                                </o>
                              </l2>
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems">
                              <o t="BoxTreeBox">
                                <v n="BoxType">"MOVE"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">825L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" cet="Operand">
                                    <n />
                                    <o>
                                      <v n="Operand">"opc.popa_0081_av_3248_hmi_position_request"</v>
                                      <v n="Type">"LREAL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">true</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">827L</v>
                                    </o>
                                  </l2>
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems">
                                  <o t="BoxTreeBox">
                                    <v n="BoxType">"MOVE"</v>
                                    <o n="Instance" t="Operand">
                                      <n n="Operand" />
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">true</v>
                                      <v n="Id">144L</v>
                                    </o>
                                    <o n="OutputItems" t="OutputItemList">
                                      <l2 n="OutputItems" cet="Operand">
                                        <n />
                                        <o>
                                          <v n="Operand">"av_3248_position_request"</v>
                                          <v n="Type">"INT"</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">true</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">146L</v>
                                        </o>
                                      </l2>
                                    </o>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <n n="InputFlags" />
                                    <l2 n="InputItems">
                                      <o t="BoxTreeBox">
                                        <v n="BoxType">"MOVE"</v>
                                        <o n="Instance" t="Operand">
                                          <n n="Operand" />
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">true</v>
                                          <v n="Id">812L</v>
                                        </o>
                                        <o n="OutputItems" t="OutputItemList">
                                          <l2 n="OutputItems" cet="Operand">
                                            <n />
                                            <o>
                                              <v n="Operand">"opc.popa_0081_av_3148_hmi_position_request"</v>
                                              <v n="Type">"LREAL"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">true</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">814L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <n n="InputFlags" />
                                        <l2 n="InputItems">
                                          <o t="BoxTreeBox">
                                            <v n="BoxType">"MOVE"</v>
                                            <o n="Instance" t="Operand">
                                              <n n="Operand" />
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">147L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems" cet="Operand">
                                                <n />
                                                <o>
                                                  <v n="Operand">"av_3148_position_request"</v>
                                                  <v n="Type">"INT"</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">true</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">false</v>
                                                  <v n="Id">149L</v>
                                                </o>
                                              </l2>
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems">
                                              <o t="BoxTreeBox">
                                                <v n="BoxType">"OR"</v>
                                                <o n="Instance" t="Operand">
                                                  <n n="Operand" />
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">true</v>
                                                  <v n="Id">427L</v>
                                                </o>
                                                <o n="OutputItems" t="OutputItemList">
                                                  <l2 n="OutputItems" />
                                                </o>
                                                <o n="Flags" t="Flags">
                                                  <v n="Flags">0</v>
                                                  <v n="Fixed">false</v>
                                                  <v n="Extensible">false</v>
                                                </o>
                                                <n n="InputFlags" />
                                                <l2 n="InputItems">
                                                  <o t="BoxTreeBox">
                                                    <v n="BoxType">"TON"</v>
                                                    <o n="Instance" t="Operand">
                                                      <v n="Operand">"tmr_stop_pump_delay"</v>
                                                      <v n="Type">"TON"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">true</v>
                                                      <v n="Id">497L</v>
                                                    </o>
                                                    <o n="OutputItems" t="OutputItemList">
                                                      <l2 n="OutputItems" cet="Operand">
                                                        <n />
                                                        <o>
                                                          <v n="Operand">"tmr_stop_pump_delay_et"</v>
                                                          <v n="Type">"TIME"</v>
                                                          <v n="Comment">""</v>
                                                          <v n="SymbolComment">""</v>
                                                          <v n="Address">""</v>
                                                          <o n="Flags" t="Flags">
                                                            <v n="Flags">0</v>
                                                            <v n="Fixed">false</v>
                                                            <v n="Extensible">false</v>
                                                          </o>
                                                          <v n="LValue">true</v>
                                                          <v n="Boolean">false</v>
                                                          <v n="IsInstance">false</v>
                                                          <v n="Id">499L</v>
                                                        </o>
                                                      </l2>
                                                    </o>
                                                    <o n="Flags" t="Flags">
                                                      <v n="Flags">0</v>
                                                      <v n="Fixed">false</v>
                                                      <v n="Extensible">false</v>
                                                    </o>
                                                    <n n="InputFlags" />
                                                    <l2 n="InputItems">
                                                      <o t="BoxTreeBox">
                                                        <v n="BoxType">"AND"</v>
                                                        <o n="Instance" t="Operand">
                                                          <n n="Operand" />
                                                          <v n="Type">""</v>
                                                          <v n="Comment">""</v>
                                                          <v n="SymbolComment">""</v>
                                                          <v n="Address">""</v>
                                                          <o n="Flags" t="Flags">
                                                            <v n="Flags">0</v>
                                                            <v n="Fixed">false</v>
                                                            <v n="Extensible">false</v>
                                                          </o>
                                                          <v n="LValue">false</v>
                                                          <v n="Boolean">false</v>
                                                          <v n="IsInstance">true</v>
                                                          <v n="Id">500L</v>
                                                        </o>
                                                        <o n="OutputItems" t="OutputItemList">
                                                          <l2 n="OutputItems" />
                                                        </o>
                                                        <o n="Flags" t="Flags">
                                                          <v n="Flags">0</v>
                                                          <v n="Fixed">false</v>
                                                          <v n="Extensible">false</v>
                                                        </o>
                                                        <n n="InputFlags" />
                                                        <l2 n="InputItems" cet="BoxTreeOperand">
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"general.ed_routine_stop"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">0</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">236L</v>
                                                            </o>
                                                            <v n="Id">235L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3112_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">488L</v>
                                                            </o>
                                                            <v n="Id">487L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3212_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">246L</v>
                                                            </o>
                                                            <v n="Id">245L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3312_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">244L</v>
                                                            </o>
                                                            <v n="Id">243L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3405_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">242L</v>
                                                            </o>
                                                            <v n="Id">241L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3160_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">240L</v>
                                                            </o>
                                                            <v n="Id">239L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3260_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">155L</v>
                                                            </o>
                                                            <v n="Id">154L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3360_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">238L</v>
                                                            </o>
                                                            <v n="Id">237L</v>
                                                          </o>
                                                          <o>
                                                            <o n="Operand" t="Operand">
                                                              <v n="Operand">"faults.u_3370_fail_to_stop.trigger"</v>
                                                              <v n="Type">"BOOL"</v>
                                                              <v n="Comment">""</v>
                                                              <v n="SymbolComment">""</v>
                                                              <v n="Address">""</v>
                                                              <o n="Flags" t="Flags">
                                                                <v n="Flags">1</v>
                                                                <v n="Fixed">true</v>
                                                                <v n="Extensible">false</v>
                                                              </o>
                                                              <v n="LValue">false</v>
                                                              <v n="Boolean">true</v>
                                                              <v n="IsInstance">false</v>
                                                              <v n="Id">169L</v>
                                                            </o>
                                                            <v n="Id">168L</v>
                                                          </o>
                                                        </l2>
                                                        <o n="InputParam" t="ParamList">
                                                          <l2 n="Names" />
                                                          <l2 n="Types" />
                                                        </o>
                                                        <o n="OutputParam" t="ParamList">
                                                          <l2 n="Names" />
                                                          <l2 n="Types" />
                                                        </o>
                                                        <v n="CallType" t="Operator">And</v>
                                                        <n n="EN" />
                                                        <n n="ENO" />
                                                        <n n="STSnippet" />
                                                        <v n="ContainsExtensibleInputs">false</v>
                                                        <v n="ProvidesSTSnippet">false</v>
                                                        <v n="Id">501L</v>
                                                      </o>
                                                      <o t="BoxTreeOperand">
                                                        <o n="Operand" t="Operand">
                                                          <v n="Operand">"tmr_stop_pump_delay_pt"</v>
                                                          <v n="Type">"TIME"</v>
                                                          <v n="Comment">""</v>
                                                          <v n="SymbolComment">""</v>
                                                          <v n="Address">""</v>
                                                          <o n="Flags" t="Flags">
                                                            <v n="Flags">0</v>
                                                            <v n="Fixed">false</v>
                                                            <v n="Extensible">false</v>
                                                          </o>
                                                          <v n="LValue">false</v>
                                                          <v n="Boolean">false</v>
                                                          <v n="IsInstance">false</v>
                                                          <v n="Id">503L</v>
                                                        </o>
                                                        <v n="Id">502L</v>
                                                      </o>
                                                    </l2>
                                                    <o n="InputParam" t="ParamList">
                                                      <l2 n="Names" cet="String">
                                                        <v>IN</v>
                                                        <v>PT</v>
                                                      </l2>
                                                      <l2 n="Types" cet="String">
                                                        <v>BOOL</v>
                                                        <v>TIME</v>
                                                      </l2>
                                                    </o>
                                                    <o n="OutputParam" t="ParamList">
                                                      <l2 n="Names" cet="String">
                                                        <v>Q</v>
                                                        <v>ET</v>
                                                      </l2>
                                                      <l2 n="Types" cet="String">
                                                        <v>BOOL</v>
                                                        <v>TIME</v>
                                                      </l2>
                                                    </o>
                                                    <v n="CallType" t="Operator">FunctionBlock</v>
                                                    <v n="EN">false</v>
                                                    <v n="ENO">false</v>
                                                    <n n="STSnippet" />
                                                    <v n="ContainsExtensibleInputs">false</v>
                                                    <v n="ProvidesSTSnippet">false</v>
                                                    <v n="Id">498L</v>
                                                  </o>
                                                  <o t="BoxTreeOperand">
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"general.ed_critical_stop"</v>
                                                      <v n="Type">"BOOL"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">true</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">true</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">432L</v>
                                                    </o>
                                                    <v n="Id">431L</v>
                                                  </o>
                                                </l2>
                                                <o n="InputParam" t="ParamList">
                                                  <l2 n="Names" />
                                                  <l2 n="Types" />
                                                </o>
                                                <o n="OutputParam" t="ParamList">
                                                  <l2 n="Names" />
                                                  <l2 n="Types" />
                                                </o>
                                                <v n="CallType" t="Operator">Or</v>
                                                <n n="EN" />
                                                <n n="ENO" />
                                                <n n="STSnippet" />
                                                <v n="ContainsExtensibleInputs">false</v>
                                                <v n="ProvidesSTSnippet">false</v>
                                                <v n="Id">428L</v>
                                              </o>
                                              <o t="BoxTreeOperand">
                                                <o n="Operand" t="Operand">
                                                  <v n="Operand">"100"</v>
                                                  <v n="Type">"INT"</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">false</v>
                                                  <v n="Id">171L</v>
                                                </o>
                                                <v n="Id">170L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>EN</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>ENO</v>
                                                <v></v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                                <v></v>
                                              </l2>
                                            </o>
                                            <v n="CallType" t="Operator">Move</v>
                                            <v n="EN">true</v>
                                            <v n="ENO">true</v>
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">148L</v>
                                          </o>
                                          <o t="BoxTreeOperand">
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"100"</v>
                                              <v n="Type">"INT"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">816L</v>
                                            </o>
                                            <v n="Id">815L</v>
                                          </o>
                                        </l2>
                                        <o n="InputParam" t="ParamList">
                                          <l2 n="Names" cet="String">
                                            <v>EN</v>
                                          </l2>
                                          <l2 n="Types" cet="String">
                                            <v>BOOL</v>
                                          </l2>
                                        </o>
                                        <o n="OutputParam" t="ParamList">
                                          <l2 n="Names" cet="String">
                                            <v>ENO</v>
                                            <v></v>
                                          </l2>
                                          <l2 n="Types" cet="String">
                                            <v>BOOL</v>
                                            <v></v>
                                          </l2>
                                        </o>
                                        <v n="CallType" t="Operator">Move</v>
                                        <v n="EN">true</v>
                                        <v n="ENO">true</v>
                                        <n n="STSnippet" />
                                        <v n="ContainsExtensibleInputs">false</v>
                                        <v n="ProvidesSTSnippet">false</v>
                                        <v n="Id">813L</v>
                                      </o>
                                      <o t="BoxTreeOperand">
                                        <o n="Operand" t="Operand">
                                          <v n="Operand">"100"</v>
                                          <v n="Type">"INT"</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">173L</v>
                                        </o>
                                        <v n="Id">172L</v>
                                      </o>
                                    </l2>
                                    <o n="InputParam" t="ParamList">
                                      <l2 n="Names" cet="String">
                                        <v>EN</v>
                                      </l2>
                                      <l2 n="Types" cet="String">
                                        <v>BOOL</v>
                                      </l2>
                                    </o>
                                    <o n="OutputParam" t="ParamList">
                                      <l2 n="Names" cet="String">
                                        <v>ENO</v>
                                        <v></v>
                                      </l2>
                                      <l2 n="Types" cet="String">
                                        <v>BOOL</v>
                                        <v></v>
                                      </l2>
                                    </o>
                                    <v n="CallType" t="Operator">Move</v>
                                    <v n="EN">true</v>
                                    <v n="ENO">true</v>
                                    <n n="STSnippet" />
                                    <v n="ContainsExtensibleInputs">false</v>
                                    <v n="ProvidesSTSnippet">false</v>
                                    <v n="Id">145L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"100"</v>
                                      <v n="Type">"INT"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">829L</v>
                                    </o>
                                    <v n="Id">828L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" cet="String">
                                    <v>EN</v>
                                  </l2>
                                  <l2 n="Types" cet="String">
                                    <v>BOOL</v>
                                  </l2>
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" cet="String">
                                    <v>ENO</v>
                                    <v></v>
                                  </l2>
                                  <l2 n="Types" cet="String">
                                    <v>BOOL</v>
                                    <v></v>
                                  </l2>
                                </o>
                                <v n="CallType" t="Operator">Move</v>
                                <v n="EN">true</v>
                                <v n="ENO">true</v>
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">826L</v>
                              </o>
                              <o t="BoxTreeOperand">
                                <o n="Operand" t="Operand">
                                  <v n="Operand">"100"</v>
                                  <v n="Type">"INT"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">175L</v>
                                </o>
                                <v n="Id">174L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v>EN</v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                              </l2>
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v>ENO</v>
                                <v></v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                                <v></v>
                              </l2>
                            </o>
                            <v n="CallType" t="Operator">Move</v>
                            <v n="EN">true</v>
                            <v n="ENO">true</v>
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">142L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"100"</v>
                              <v n="Type">"INT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">824L</v>
                            </o>
                            <v n="Id">823L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v></v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v></v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">Move</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">821L</v>
                      </o>
                      <v n="Id">182L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">140L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EQ"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">282L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <n />
                          <o>
                            <v n="Operand">"av_3348_recycle_position"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">284L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems">
                        <o t="BoxTreeBox">
                          <v n="BoxType">"EQ"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">223L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"av_3248_recycle_position"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">225L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"EQ"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">216L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" cet="Operand">
                                  <n />
                                  <o>
                                    <v n="Operand">"av_3148_recycle_position"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">true</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">218L</v>
                                  </o>
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeOperand">
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"general.ed_routine_stop"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">true</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">215L</v>
                                  </o>
                                  <v n="Id">214L</v>
                                </o>
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"100"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">220L</v>
                                  </o>
                                  <v n="Id">219L</v>
                                </o>
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"av_3148_position_feedback"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">222L</v>
                                  </o>
                                  <v n="Id">221L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>EN</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>ENO</v>
                                  <v></v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Eq</v>
                              <v n="EN">true</v>
                              <v n="ENO">true</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">217L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"100"</v>
                                <v n="Type">"INT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">227L</v>
                              </o>
                              <v n="Id">226L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"nv_3335_position_feedback"</v>
                                <v n="Type">"INT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">229L</v>
                              </o>
                              <v n="Id">228L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>EN</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>ENO</v>
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Eq</v>
                          <v n="EN">true</v>
                          <v n="ENO">true</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">224L</v>
                        </o>
                        <o t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"100"</v>
                            <v n="Type">"INT"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">286L</v>
                          </o>
                          <v n="Id">285L</v>
                        </o>
                        <o t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"av_3348_position_feedback"</v>
                            <v n="Type">"INT"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">288L</v>
                          </o>
                          <v n="Id">287L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                          <v></v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Eq</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">283L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">201L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"ed_valves_stopped"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">82L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"AND"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">""</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">118L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" />
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"general.ed_routine_stop"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">234L</v>
                            </o>
                            <v n="Id">233L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"io_mapping.nv_3110_closed_feedback"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">191L</v>
                            </o>
                            <v n="Id">190L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"io_mapping.nv_3210_closed_feedback"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">189L</v>
                            </o>
                            <v n="Id">188L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"io_mapping.nv_3310_closed_feedback"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">187L</v>
                            </o>
                            <v n="Id">186L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"io_mapping.nv_3135_closed_feedback"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">185L</v>
                            </o>
                            <v n="Id">184L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"io_mapping.nv_3235_closed_feedback"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">294L</v>
                            </o>
                            <v n="Id">293L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"nv_3335_closed_feedback"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">292L</v>
                            </o>
                            <v n="Id">291L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"nv_3372_closed_feedback"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">255L</v>
                            </o>
                            <v n="Id">254L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"av_3148_recycle_position"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">253L</v>
                            </o>
                            <v n="Id">252L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"av_3248_recycle_position"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">290L</v>
                            </o>
                            <v n="Id">289L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"av_3348_recycle_position"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">251L</v>
                            </o>
                            <v n="Id">250L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <v n="CallType" t="Operator">And</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">119L</v>
                      </o>
                      <v n="Id">79L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">39L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"ramp"</v>
                      <o n="Instance" t="Operand">
                        <v n="Operand">"test_ramp"</v>
                        <v n="Type">"ramp"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">665L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"test_ramp_duration"</v>
                            <v n="Type">"INT"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">668L</v>
                          </o>
                          <v n="Id">667L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"test_ramp_start_val"</v>
                            <v n="Type">"REAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">670L</v>
                          </o>
                          <v n="Id">669L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"test_ramp_end_val"</v>
                            <v n="Type">"REAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">672L</v>
                          </o>
                          <v n="Id">671L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"eng_test"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">674L</v>
                          </o>
                          <v n="Id">673L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>duration</v>
                          <v>start_val</v>
                          <v>end_val</v>
                          <v>enable</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>INT</v>
                          <v>REAL</v>
                          <v>REAL</v>
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>output</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>REAL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">FunctionBlock</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">666L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">664L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"ed_stopped"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">266L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"AND"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">"AND"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">260L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" />
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"stack_power_enabled"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">1</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">265L</v>
                            </o>
                            <v n="Id">264L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"ed_pumps_stopped"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">263L</v>
                            </o>
                            <v n="Id">262L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"ed_valves_stopped"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">259L</v>
                            </o>
                            <v n="Id">258L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <v n="CallType" t="Operator">And</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">261L</v>
                      </o>
                      <v n="Id">267L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">257L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>